pipeline {
    agent any
    tools {
        jdk 'jdk17'
        nodejs 'node16'
    }
    environment {
        SCANNER_HOME=tool 'mysonar'
    }
        stage ("git checkout") {
            steps {
                git branch: 'main', credentialsId: 'Github_user', url: 'https://github.com/ramakrishna-k7/tetris-k8.git'
            }
        }
        stage("code quality") {
            steps{
                withSonarQubeEnv('mysonar') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=zomato \
                    -Dsonar.projectKey=zomato '''
                }
            }
        }
        stage ("install dependencies") {
            steps {
                sh 'npm install'
            }
        }
        stage ("check dependencies") {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'Dp-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
         stage ("Build image") {
            steps {
                sh 'docker build -t image1 .'
            }
        }
         stage ("trivy image Scan") {
            steps {
                sh "trivy fs . > trivyfs.txt"
                sh 'trivy image ramakrishna737/game:v1'
            }
        }
        stage("Push to dockerhub"){
            steps{
                script{
                    withDockerRegistry(credentialsId: 'docker-password') {
                        sh "docker tag image1 ramakrishna737/game:v1"
                        sh "docker push ramakrishna737/game:v1"
                    }
                }
            }
        }
    }
}
